import Foundation
import NetworkCore
import DiagnosticsEngine

public struct AuditReportExporter: Sendable {
    public init() {}

    /// Exports a complete diagnostic result as a clean, professional Markdown report.
    public static func exportMarkdown(result: DiagnosticResult) -> String {
        var md = """
        # Diagnostic Evidence Report
        **Target**: `\(result.target.displayString)` (\(result.target.targetType.rawValue))  
        **Timestamp**: \(result.timestamp.formatted(date: .abbreviated, time: .standard))  
        **Overall Status**: **\(result.overallStatus.rawValue)**  
        **Executive Summary**: \(result.overallSummary)  

        ---

        ## Analytical Findings

        | Classification | Severity | Finding | Fault Domain | Confidence |
        | :--- | :--- | :--- | :--- | :--- |
        """

        for f in result.findings {
            md += "\n| `\(f.classification.rawValue)` | **\(f.severity.rawValue)** | \(f.statement) | \(f.faultDomain) | \(f.confidence.rawValue) |"
        }

        md += "\n\n---\n\n## Multi-Layer Observations\n\n"

        // DNS
        if let dns = result.dns {
            md += """
            ### 1. DNS Resolution
            - **Status**: \(dns.isHealthy ? "Healthy" : "Failed")
            - **Query Latency**: \(String(format: "%.1f", dns.queryTimeMs)) ms
            - **IPv4 Addresses**: \(dns.ipv4Addresses.map(\.description).joined(separator: ", "))
            - **IPv6 Addresses**: \(dns.ipv6Addresses.isEmpty ? "None" : dns.ipv6Addresses.map(\.description).joined(separator: ", "))

            """
        }

        // Latency
        if let lat = result.latency {
            md += """
            ### 2. Transport Latency & Jitter
            - **Probes Sent**: \(lat.sent), **Received**: \(lat.received), **Loss**: \(String(format: "%.1f", lat.lossPercentage))%
            - **Min / Max / Avg**: \(String(format: "%.1f", lat.minMs)) / \(String(format: "%.1f", lat.maxMs)) / \(String(format: "%.1f", lat.avgMs)) ms
            - **Median (P50)**: \(String(format: "%.1f", lat.medianMs)) ms
            - **P95 Latency**: \(String(format: "%.1f", lat.p95Ms)) ms
            - **RFC 3550 Jitter**: \(String(format: "%.1f", lat.jitterMs)) ms

            """
        }

        // Path
        if let path = result.path {
            md += """
            ### 3. Route Path Traversal
            - **Total Hops**: \(path.totalHops)
            - **Destination Reached**: \(path.finalHopReached ? "Yes" : "No")

            | Hop | Address | Round-Trip (ms) | Status |
            | :--- | :--- | :--- | :--- |
            """
            for h in path.hops {
                let addr = h.address ?? "*"
                let rtt = h.rttMs != nil ? String(format: "%.1f", h.rttMs!) : "-"
                let status = h.isTimeout ? "Timed out" : "Responded"
                md += "\n| \(h.hopNumber) | `\(addr)` | \(rtt) | \(status) |"
            }
            md += "\n\n"
        }

        // HTTP/TLS
        if let http = result.http {
            md += """
            ### 4. Application & TLS Layer
            - **HTTP Status**: \(http.statusCode)
            - **Total Request Time**: \(String(format: "%.1f", http.totalTimeMs)) ms
            - **Time to First Byte (TTFB)**: \(http.ttfbMs != nil ? String(format: "%.1f ms", http.ttfbMs!) : "N/A")
            - **TLS Certificate**: \(http.certificateInfo?.subjectSummary ?? "N/A")
            - **Days Remaining**: \(http.certificateInfo?.daysUntilExpiry != nil ? "\(http.certificateInfo!.daysUntilExpiry!) days" : "N/A")

            """
        }

        md += """
        ---
        *Generated by NexWave Network Workbench on macOS.*  
        *All diagnostic measurements performed locally.*
        """

        return md
    }
}
